### ISSUE TITLE
macros not work in mk11 properly

### ISSUE THREAD

**Issue by AjinkyaBhutkar98** [1vanK/MaKros#1]
i tried to make macros using you files and your videos but its doesnt execute propely it hits the button 1 or 2 times properly after that it perform diffrent moves than typed ones can you please make videos on making macro on mk11

**Comment by 1vanK** [comment]
https://github.com/1vanK/MaKros/blob/master/%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE/03%20%D0%9F%D0%BE%D0%B4%D1%80%D0%BE%D0%B1%D0%BD%D0%B5%D0%B5.txt#L126-L127
