### ISSUE TITLE
erron black mk11 locked and loaded cancel 

### ISSUE THREAD

**Issue by Ilovemortalkombat** [1vanK/MaKros#5]
there is a move in mk11 erron black that need to hold up to  cancel his 1 move how to cancel it can you please add command to hold key

**Comment by 1vanK** [comment]
Use KeyDown and KeyUp instead KeyPress.

Example: https://github.com/1vanK/MaKros/blob/master/%D0%9F%D1%80%D0%B8%D0%BC%D0%B5%D1%80%D1%8B/%D0%9E%D1%82%D0%BC%D0%B5%D0%BD%D0%B0%20%D0%BE%D0%B4%D0%BD%D0%BE%D0%B9%20%D0%BA%D0%BD%D0%BE%D0%BF%D0%BA%D0%BE%D0%B9%20(Scorpion%20Hellfire)/Script.cs

**Comment by Ilovemortalkombat** [comment]
thanks
