### ISSUE TITLE
Combo issues sometime in online

### ISSUE THREAD

**Issue by Ilovemortalkombat** [1vanK/MaKros#6]
hello sir thanks for solving my last issue the thing is the combos sometime works perfect in online matches but sometime when i press hotkey like f after blocking some attacks from opponent it uses random moves i turned on online input delay on and release check off also i used unpressallkeys command is there anyway i can fix this thanks

**Comment by 1vanK** [comment]
Possible you start the combos too early when your character is still in blockstun and the game just drop first key presses. In blockstun you can input only specials. This buffered specials are called reversals.
